export const PRIVACY_POLICY = `
# Privacy Policy
Last updated: April 2026

Task Shredder AI ("we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how your information is collected, used, and safeguarded.

## 1. Information We Collect
- **Telegram Data**: We receive basic information from Telegram (User ID, First Name, Username) through the Mini App SDK.
- **Task Data**: Any text you enter for "shredding" is processed by our AI models.
- **Local Data**: Your AI credits and session history are stored locally on your device via LocalStorage.

## 2. Third-Party Services
- **Groq Cloud AI**: We use Groq as our primary generative AI provider. Task inputs are sent to their servers for processing but are not used for training data by us.
- **AdsGram**: We use AdsGram for rewarded ad displays. They may collect basic technical identifiers to serve relevant ads.

## 3. Data Retention
We do not maintain a permanent database of your tasks. History is stored on your device and can be cleared by you at any time.

## 4. Contact
For questions regarding this policy, please contact us via Telegram: @Kalai_Developer
`;

export const TERMS_OF_USE = `
# Terms of Use
Last updated: April 2026

By using Task Shredder AI, you agree to these terms. Please read them carefully.

## 1. Acceptance of Terms
Accessing this Telegram Mini App constitutes your agreement to be bound by these Terms of Use and all applicable laws and regulations.

## 2. AI disclaimer
- **Accuracy**: The task breakdowns generated by AI are for guidance purposes only. We do not guarantee the completeness or absolute accuracy of generated strategies.
- **Liability**: Task Shredder AI is not responsible for any outcomes, losses, or missed deadlines resulting from the use of AI-generated advice.

## 3. Credits & Payments
- Credits are consumed for each AI generation.
- Users can earn credits by watching ads or purchasing them via Telegram Stars.
- All purchases are final according to Telegram's digital goods policies.

## 4. Prohibited Use
You agree not to use the app for any illegal purposes or to submit harmful, offensive, or malicious content for processing.

---
© 2026 TASK SHREDDER AI
`;
